services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command: [
      "--jetstream",
      "--store_dir=/data"
    ]
    volumes:
      - nats_data:/data

  nats-firehose-ingest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nats-firehose-ingest
    depends_on:
      - nats
    env_file:
      - .env.local
    environment:
      NATS_URL: "nats://nats:4222"
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    environment:
      NATS_URL: "nats://nats:4222"
    profiles:
      - tools
    tty: true
    stdin_open: true

volumes:
  nats_data:
    driver: local
  nui_db:
    driver: local
