# Default values for nats-firehose-ingest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replica count for the deployment
replicaCount: 1

# Container image configuration
image:
  repository: ghcr.io/richardr1126/nats-firehose-ingest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

# Image pull secrets for private registries
imagePullSecrets: []

# Override chart names
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security contexts
podSecurityContext:
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Resource limits and requests
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Health check probes
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Environment configuration
envFrom:
  - secretRef:
      name: nats-firehose-ingest-env
  # You can add additional envFrom sources like configMaps:
  # - configMapRef:
  #     name: nats-firehose-ingest-config

# Node selector, tolerations, and affinity
nodeSelector: {}
tolerations: []
affinity: {}
